### ISSUE TITLE
I don’t think anybody in their right mind would use NIO to implement an HTTP server at a high level

### ISSUE THREAD

**Issue by Frizlab** [begoon/http-server#2]
So I’m not sure what the goal of the repo is here, but if I wanted to implement a web server I’d use [Vapor](https://github.com/vapor/vapor) or [Hummingbird](https://github.com/hummingbird-project/hummingbird), _not_ NIO which is a low-level package (both Vapor and Hummingbird do use it behind the scene).

Using Vapor the whole server looks like this (require the installation of swift-sh (`brew install xcode-actions/tap/swift-sh`) to run in a single file, but using an actual package with a `Package.swift` works too):
```swift
#!/usr/bin/env -S swift-sh --

import Foundation

import Vapor // @vapor/vapor ~> 4.0



struct Version : Content {
	var version: String = "1.0.0"
}

struct Main {

	static func main() async {
		do {
			let app = try await Application.make()
			app.get("version", use: { _ in Version() })
			try await app.execute()
			try await app.asyncShutdown()
		} catch {
			print("got error: \(error)")
		}
	}

}
_ = await Task{ await Main.main() }.value
```

**Comment by begoon** [comment]
Thanks for the contribution. Your PR is merged.
